# Generated by Django 3.0.6 on 2021-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('brought', 'Brought'), ('not available', 'Not Available'), ('pending', 'Pending')], max_length=20),
        ),
    ]
